<a href="https://colab.research.google.com/github/cai4cai/PyTorchFromCPPTest/blob/main/pytorchfromcpptest_colabcudatest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
print(sys.version)
!/usr/local/bin/python --version

3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Python 3.10.6


In [2]:
!pip3 install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!rm -f main.zip*
!wget https://github.com/cai4cai/PyTorchFromCPPTest/archive/refs/heads/main.zip
!unzip -o main.zip
# There is an old version of pathlib living in /usr/local/lib/python3.10/dist-packages/
# Let the one in /usr/lib/python3.10/dist-packages/ be used
!rm /usr/local/lib/python3.10/dist-packages/pathlib.py
!mkdir -p build
!cd build; cmake ../PyTorchFromCPPTest-main
!cd build; make

Looking in indexes: https://download.pytorch.org/whl/cu118
--2023-07-29 15:42:15--  https://github.com/cai4cai/PyTorchFromCPPTest/archive/refs/heads/main.zip
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/cai4cai/PyTorchFromCPPTest/zip/refs/heads/main [following]
--2023-07-29 15:42:16--  https://codeload.github.com/cai4cai/PyTorchFromCPPTest/zip/refs/heads/main
Resolving codeload.github.com (codeload.github.com)... 140.82.121.10
Connecting to codeload.github.com (codeload.github.com)|140.82.121.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘main.zip’

main.zip                [ <=>                ]  17.44K  --.-KB/s    in 0.007s  

2023-07-29 15:42:16 (2.47 MB/s) - ‘main.zip’ saved [17860]

Archive:  main.zip
e15b6fb2b6e8da212dc57b072356511af2b30370
   creat

In [3]:
!./build/pytorchfromcpptest

Starting test from c++
PyTorch version: 2.0.1
CUDA is available. Running on GPU.
Random 2x3 tensor (c++ side):
 0.1436  0.1151  0.7989
 0.4608  0.8150  0.1522
[ CUDAFloatType{2,3} ]
Custom python module loaded from /content/PyTorchFromCPPTest-main
Start python op
tensor([[0.1436, 0.1151, 0.7989],
        [0.4608, 0.8150, 0.1522]], device='cuda:0')
Python return value 
 0.2872  0.2303  1.5978
 0.9215  1.6300  0.3043
[ CUDAFloatType{2,3} ]


In [4]:
!./build/pytorchfromcpptestwiththreadedloop

Starting test from c++
PyTorch version: 2.0.1
CUDA is available. Running on GPU.
Example globaltensor (c++ side):
 0
 1
 2
[ CUDALongType{3} ]
Custom python module loaded from /content/PyTorchFromCPPTest-main
Launching thread at iter 0 with cloned tensor 
 0
 1
 2
[ CUDALongType{3} ]
Start python op
tensor([0, 1, 2], device='cuda:0')
tensor([0, 1, 2], device='cuda:0')
Thread is busy at iter 1
Thread is busy at iter 2
Thread is busy at iter 3
Thread is busy at iter 4
Thread is busy at iter 5
Thread is busy at iter 6
Thread is busy at iter 7
Thread is busy at iter 8
Thread is busy at iter 9
Thread is busy at iter 10
Python return value (in c++) 
 0
 2
 4
[ CUDALongType{3} ]
Launching thread at iter 11 with cloned tensor 
 11
 12
 13
[ CUDALongType{3} ]
Start python op
tensor([0, 1, 2], device='cuda:0')
tensor([11, 12, 13], device='cuda:0')
Thread is busy at iter 12
Thread is busy at iter 13
Thread is busy at iter 14
Thread is busy at iter 15
Thread is busy at iter 16
Thread is busy at it